source ./plugins.vim
source ./general.vim
source ./display.vim
source ./spelling.vim
source ./keymaps.vim
source ./nerdtree.vim
source ./ctrlp.vim
source ./ultisnips.vim
source ./go.vim
source ./git.vim
source ./neomake.vim
source ./ruby.vim
source ./javascript.vim
source ./css.vim
source ./html.vim
source ./markdown.vim
source ./closetag.vim
source ./tagbar.vim
source ./tmux.vim
source ./ycm.vim
source ./lush.vim
source ./peg.vim
